name: Build and Publish Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Convert repository owner to lowercase
              id: repo
              run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ env.REPO_OWNER }}/kaetram:${{ github.sha }}
                  cache-from: type=registry,ref=ghcr.io/${{ env.REPO_OWNER }}/kaetram:cache
                  cache-to: type=inline

            - name: Tag image with "latest"
              if: github.ref == 'refs/heads/main'
              run: |
                  docker tag ghcr.io/${{ env.REPO_OWNER }}/kaetram:${{ github.sha }} ghcr.io/${{ env.REPO_OWNER }}/kaetram:latest
                  docker push ghcr.io/${{ env.REPO_OWNER }}/kaetram:latest
